<a href="https://colab.research.google.com/github/sarthak572/cognitive_computing/blob/main/assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = [1,2,3,4,5]
arr = np.array(a)

print(f"1. {arr[1] + arr[2]}")
print(f"2. {arr * 3}")
print(f"3. {arr / 2}")

1. 5
2. [ 3  6  9 12 15]
3. [0.5 1.  1.5 2.  2.5]


In [2]:
arr = np.array([1,2,3,4,5])
print(f"Reversed array: {np.flip(arr)}")

x = np.array([1,2,3,4,5,1,2,1,1,1])
unq_x, counts_x = np.unique(x, return_counts=True)
max_counts_x = np.argmax(counts_x)
max_element_x = unq_x[max_counts_x]
print(f"Most frequent element in x: {max_element_x}, with a frequency of: {counts_x[max_counts_x]}")

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
unq_y, counts_y = np.unique(y, return_counts=True)
max_counts_y = np.argmax(counts_y)
max_element_y = unq_y[max_counts_y]
print(f"Most frequent element in x: {max_element_y}, with a frequency of: {counts_y[max_counts_y]}")

Reversed array: [5 4 3 2 1]
Most frequent element in x: 1, with a frequency of: 5
Most frequent element in x: 1, with a frequency of: 3


In [3]:
arr2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(f"1. {arr2d[0][1]}")
print(f"2. {arr2d[2][0]}")

1. 20
2. 70


In [4]:
import numpy as np

sarthak = np.array(np.linspace(10, 100, 25), dtype=np.float64)

print(f"i.\nDimensions: {sarthak.ndim}")
print(f"Shape: {sarthak.shape}")
print(f"Number of elements: {sarthak.size}")
print(f"Datatype: {sarthak.dtype}")
print(f"Number of Bytes occupied: {sarthak.nbytes}")

sarthak_reshaped = sarthak.reshape(5, 5)
print(f"ii. Transpose using reshape:\n{sarthak_reshaped}")

sarthak_T = sarthak_reshaped.T
print(f"Transpose using T attribute:\n{sarthak_T}")

i.
Dimensions: 1
Shape: (25,)
Number of elements: 25
Datatype: float64
Number of Bytes occupied: 200
ii. Transpose using reshape:
[[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.5   96.25 100.  ]]
Transpose using T attribute:
[[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]


In [5]:
import numpy as np

ucs420_Shrey = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35])

print(f"Mean: {ucs420_Shrey.mean():.3f}")
print(f"Median: {np.median(ucs420_Shrey)}")
print(f"Max: {ucs420_Shrey.max()}")
print(f"Min: {ucs420_Shrey.min()}")

print(f"Standard Deviation: {ucs420_Shrey.std():.3f}")
print(f"Variance: {ucs420_Shrey.var():.3f}")

unique_elements = np.unique(ucs420_Shrey)
print(f"Unique elements: {unique_elements}")

sorted_array = np.sort(ucs420_Shrey)
print(f"Sorted array: {sorted_array}")

if ucs420_Shrey.size == 4 * 3:
    reshaped_array = ucs420_Shrey.reshape(4, 3)
    print(f"Reshaped array (4x3):\n{reshaped_array}")
else:
    print("Reshape operation skipped: Invalid size.")

resized_array = np.resize(ucs420_Shrey, (2, 3))
print(f"Resized array (2x3):\n{resized_array}")


Mean: 43.333
Median: 37.5
Max: 90
Min: 10
Standard Deviation: 25.522
Variance: 651.389
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Sorted array: [10 15 20 20 30 35 40 50 60 70 80 90]
Reshaped array (4x3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array (2x3):
[[10 20 30]
 [40 50 60]]
